export const CATEGORIES = [
  { value: '', text: 'None' },
  { value: 'Fruits', text: '🍎 Fruits' },
  { value: 'Vegetables', text: '🥬 Vegetables' },
  { value: 'Meat', text: '🍖 Meat' },
  { value: 'Seafood', text: '🦐 Seafood' },
  { value: 'Frozen', text: '❄️ Frozen' },
  { value: 'Cold cuts', text: '🥩 Cold cuts' },
  { value: 'Dairy', text: '🥚 Dairy' },
  { value: 'Bread', text: '🍞 Bread' },
  { value: 'Malay Dish', text: '🥘 Malay Dish' },
  { value: 'Cake and biscuits', text: '🍰 Cake and biscuits' },
  { value: 'Beverage', text: '🧃 Beverage' },
  { value: 'Coffee and Tea', text: '☕️ Coffee and Tea' },
  { value: 'Milk and Chocolate', text: '🥛 Milk and Chocolate' },
  { value: 'Snacks', text: '🥨 Snacks' },
  { value: 'Sweets', text: '🍬 Sweets' },
  { value: 'Condiment and Dips', text: '🫕 Condiment and Dips' },
  { value: 'Dry Goods', text: '🫙 Dry Goods' },
  { value: 'Cooking ingridients', text: '🍳 Cooking ingridients' },
  { value: 'Nuts and Seeds', text: '🥜 Nuts and Seeds' },
  { value: 'Canned Food', text: '🥫 Canned Food' },
  { value: 'Cereals', text: '🥣 Cereals' },
  { value: 'Leftovers', text: '🥘 Leftovers' },
  { value: 'Easy Meals', text: '🍕 Easy Meals' },
  { value: 'ousehold Essentials', text: '🧂 Household Essentials' },
  { value: 'Baking Goods', text: '🥖 Baking Goods' },
  { value: 'Other Goods', text: '🍜 Other Goods' },
];
